export const GET_USER_DEVICES = 'GET_USER_DEVICES';
export const GET_CURRENT_DEVICE = 'GET_CURRENT_DEVICE';
export const GET_CURRENT_DEVICE_SECTORS = 'GET_CURRENT_DEVICE_SECTORS';

export const CREATE_DEVICE = 'CREATE_DEVICE';
export const CREATE_DEVICE_SECTORS = 'CREATE_DEVICE_SECTORS';

export const DELETE_DEVICE = 'DELETE_DEVICE';
export const DELETE_SECTOR = 'DELETE_SECTOR';

export const GET_DEVICE_SERVICE_STAT = 'GET_DEVICE_SERVICE_STAT';
export const GET_DEVICE_SECTORS_WORK_STAT = 'GET_DEVICE_SECTORS_WORK_STAT';

export const START_SERVICE = 'START_SERVICE';
export const STOP_SERVICE = 'STOP_SERVICE';
