export const GET_USER_DEVICES = 'GET_USER_DEVICES';
export const GET_CURRENT_DEVICE = 'GET_CURRENT_DEVICE';
export const GET_CURRENT_DEVICE_SECTORS = 'GET_CURRENT_DEVICE_SECTORS';
export const CREATE_DEVICE = 'CREATE_DEVICE';
export const CREATE_DEVICE_SECTORS = 'CREATE_DEVICE_SECTORS';
export const DELETE_DEVICE = 'DELETE_DEVICE';
export const DELETE_SECTOR = 'DELETE_SECTOR';
