export const SET_USER_DEVICES = 'SET_USER_DEVICES';
export const SET_CURRENT_DEVICE = 'SET_CURRENT_DEVICE';
export const SET_CURRENT_DEVICE_SECTORS = 'SET_CURRENT_DEVICE_SECTORS';
export const SET_CREATED_DEVICE = 'SET_CREATED_DEVICE';
export const SET_CREATED_SECTORS = 'SET_CREATED_SECTORS';
