export const SET_USER_DEVICES = 'SET_USER_DEVICES';
export const SET_CURRENT_DEVICE = 'SET_CURRENT_DEVICE';
export const SET_CURRENT_DEVICE_SECTORS = 'SET_CURRENT_DEVICE_SECTORS';

export const SET_CREATED_DEVICE = 'SET_CREATED_DEVICE';
export const SET_CREATED_SECTORS = 'SET_CREATED_SECTORS';

export const DELETE_DEVICE = 'DELETE_DEVICE';
export const DELETE_SECTOR = 'DELETE_SECTOR';

export const SET_DEVICE_SERVICE_STAT = 'SET_DEVICE_SERVICE_STAT';
export const SET_DEVICE_SECTORS_WORK_STAT = 'SET_DEVICE_SECTORS_WORK_STAT';

export const SET_SERVICE_IN_PROGRESS = 'SET_SERVICE_IN_PROGRESS';
export const SET_SERVICE_FINISHED = 'SET_SERVICE_FINISHED';

export const SET_USER_TOKEN = 'SET_USER_TOKEN';
export const REMOVE_USER_TOKEN = 'REMOVE_USER_TOKEN';
